//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderHeaderId { get; set; }
        public int FoodId { get; set; }
        public int FoodQuantity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
